services:
  db:
    image: postgres:16
    container_name: campusparkdb
    restart: always
    environment:
      POSTGRES_USER: campusparking
      POSTGRES_PASSWORD: superdupersecret12345
      POSTGRES_DB: campusparking
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U campusparking"]
      interval: 5s
      timeout: 5s
      retries: 5

  web:
    build: .
    container_name: campusparking
    restart: always
    depends_on:
      db:
        condition: service_healthy
    environment:
      DATABASE_URL: "postgresql://campusparking:superdupersecret12345@db:5432/campusparking"
      FLASK_ENV: "development"
      FLASK_APP: "wsgi.py"
      PYTHONPATH: "/Backend"
    ports:
      - "5000:5000"
    volumes:
      - .:/Backend
    command: ["flask", "run", "--host=0.0.0.0"]

volumes:
  postgres_data: