"""chat cliente-valet, belongings, key handover, inspections

Revision ID: 28842ab461a9
Revises: 23fcce51aff4
Create Date: 2026-04-27 19:27:52.347873

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '28842ab461a9'
down_revision = '23fcce51aff4'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('key_handovers',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('service_id', sa.Integer(), nullable=False),
    sa.Column('valet_id', sa.Integer(), nullable=False),
    sa.Column('location_label', sa.String(length=255), nullable=False),
    sa.Column('latitude', sa.Float(), nullable=True),
    sa.Column('longitude', sa.Float(), nullable=True),
    sa.Column('evidence_photo', sa.String(), nullable=False),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('stored_at', sa.DateTime(), nullable=False),
    sa.Column('returned_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['service_id'], ['services.id'], ),
    sa.ForeignKeyConstraint(['valet_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('key_handovers', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_key_handovers_service_id'), ['service_id'], unique=False)

    op.create_table('ratings',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('service_id', sa.Integer(), nullable=False),
    sa.Column('rater_id', sa.Integer(), nullable=False),
    sa.Column('rated_user_id', sa.Integer(), nullable=False),
    sa.Column('score', sa.Integer(), nullable=False),
    sa.Column('comment', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['rated_user_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['rater_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['service_id'], ['services.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('speed_alerts',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('service_id', sa.Integer(), nullable=False),
    sa.Column('valet_id', sa.Integer(), nullable=False),
    sa.Column('speed_kmh', sa.Float(), nullable=False),
    sa.Column('speed_limit_kmh', sa.Float(), nullable=False),
    sa.Column('latitude', sa.Float(), nullable=True),
    sa.Column('longitude', sa.Float(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['service_id'], ['services.id'], ),
    sa.ForeignKeyConstraint(['valet_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('speed_alerts', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_speed_alerts_service_id'), ['service_id'], unique=False)

    op.create_table('vehicle_inspections',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('service_id', sa.Integer(), nullable=False),
    sa.Column('captured_by', sa.Integer(), nullable=False),
    sa.Column('stage', sa.String(length=10), nullable=False),
    sa.Column('photos_json', sa.Text(), nullable=False),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['captured_by'], ['users.id'], ),
    sa.ForeignKeyConstraint(['service_id'], ['services.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('vehicle_inspections', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_vehicle_inspections_service_id'), ['service_id'], unique=False)

    op.create_table('belongings',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('valet_request_id', sa.Integer(), nullable=False),
    sa.Column('service_id', sa.Integer(), nullable=True),
    sa.Column('owner_id', sa.Integer(), nullable=False),
    sa.Column('description', sa.String(length=255), nullable=False),
    sa.Column('quantity', sa.Integer(), nullable=False),
    sa.Column('photos_json', sa.Text(), nullable=True),
    sa.Column('reported_missing', sa.Boolean(), nullable=False),
    sa.Column('missing_reported_at', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('is_deleted', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['owner_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['service_id'], ['services.id'], ),
    sa.ForeignKeyConstraint(['valet_request_id'], ['valet_requests.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('belongings', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_belongings_service_id'), ['service_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_belongings_valet_request_id'), ['valet_request_id'], unique=False)

    with op.batch_alter_table('chat_messages', schema=None) as batch_op:
        batch_op.add_column(sa.Column('attachment_url', sa.String(), nullable=True))
        batch_op.alter_column('sender_role',
               existing_type=sa.VARCHAR(length=10),
               type_=sa.String(length=20),
               existing_nullable=False)

    with op.batch_alter_table('conversations', schema=None) as batch_op:
        batch_op.add_column(sa.Column('valet_request_id', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('client_id', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('valet_id', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('kind', sa.String(length=20), nullable=False))
        batch_op.alter_column('user_id',
               existing_type=sa.INTEGER(),
               nullable=True)
        batch_op.create_index(batch_op.f('ix_conversations_valet_request_id'), ['valet_request_id'], unique=False)
        batch_op.create_foreign_key(None, 'valet_requests', ['valet_request_id'], ['id'])
        batch_op.create_foreign_key(None, 'users', ['valet_id'], ['id'])
        batch_op.create_foreign_key(None, 'users', ['client_id'], ['id'])

    with op.batch_alter_table('valet_requests', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_valet_requests_client_id'))
        batch_op.drop_index(batch_op.f('ix_valet_requests_status'))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('valet_requests', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_valet_requests_status'), ['status'], unique=False)
        batch_op.create_index(batch_op.f('ix_valet_requests_client_id'), ['client_id'], unique=False)

    with op.batch_alter_table('conversations', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_index(batch_op.f('ix_conversations_valet_request_id'))
        batch_op.alter_column('user_id',
               existing_type=sa.INTEGER(),
               nullable=False)
        batch_op.drop_column('kind')
        batch_op.drop_column('valet_id')
        batch_op.drop_column('client_id')
        batch_op.drop_column('valet_request_id')

    with op.batch_alter_table('chat_messages', schema=None) as batch_op:
        batch_op.alter_column('sender_role',
               existing_type=sa.String(length=20),
               type_=sa.VARCHAR(length=10),
               existing_nullable=False)
        batch_op.drop_column('attachment_url')

    with op.batch_alter_table('belongings', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_belongings_valet_request_id'))
        batch_op.drop_index(batch_op.f('ix_belongings_service_id'))

    op.drop_table('belongings')
    with op.batch_alter_table('vehicle_inspections', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_vehicle_inspections_service_id'))

    op.drop_table('vehicle_inspections')
    with op.batch_alter_table('speed_alerts', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_speed_alerts_service_id'))

    op.drop_table('speed_alerts')
    op.drop_table('ratings')
    with op.batch_alter_table('key_handovers', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_key_handovers_service_id'))

    op.drop_table('key_handovers')
    # ### end Alembic commands ###
